apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipes-book
  template:
    metadata:
      labels:
        app: recipes-book
    spec:
      containers:
        - name: recipes-book
          image: marinamj/recipes-book:latest
          ports:
            - containerPort: 80
