apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes-book
  labels:
    app: recipes-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipes-book
  template:
    metadata:
      labels:
        app: recipes-book
    spec:
      containers:
        - name: recipes-book
          image: docker.io/marinamj/recipes-book:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
