apiVersion: v1
kind: Service
metadata:
  name: recipes-book-service
spec:
  selector:
    app: recipes-book
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
