name: Combined workflow

on:
  push:
    branches:
      - "main"
      - "trivy-test"
  pull_request:
    branches:
      - "main"

jobs:
  MainProjectActions:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

        # Run tests
      - name: Run tests
        run: npm run test

      # Run linting
      - name: Run linting
        run: npm run lint

      # Format the code
      - name: Format code
        run: npm run format

      # Build the project
      - name: Build the project
        run: npm run build

  SonarCloudScan:
    runs-on: ubuntu-latest
    needs: MainProjectActions
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=mar-ina-17_recipes-book
            -Dsonar.organization=mar-ina-17
            -Dsonar.branch.name=main
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.{ts,tsx,js,jsx}
            -Dsonar.exclusions=**/node_modules/**,**/dist/**
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.tsconfigPath=tsconfig.json

  DockerActions:
    runs-on: ubuntu-latest
    needs: ["MainProjectActions", "SonarCloudScan"]
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/recipes-book:latest .

      # Push Docker Image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/recipes-book:latest

  Trivy:
    runs-on: ubuntu-latest
    needs: ["DockerActions"]
    steps:
      # Checkout the repository
      - name: Checkout to repository
        uses: actions/checkout@v3

      # Run Trivy from repository
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.DOCKER_USERNAME }}/recipes-book:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
